/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Problem Statement : Build a project "Guess the Number" that allows user to guess the number generated by the computer and invloves the following steps:
// 1.The system generates a random number from a given range, say 1 to 100
// 2.The user is prompted to enter their given number in a displayed dialog box
// 3.The computer then tells if the entered number matches the guesses number or it is higher/lower than the generated number
// 4.The game continues under the user guessing the number.
// You can also incorporated further details as:
// a.Limiting the number of attempts
// b.Adding more rounds
// c.Displaying score
// d.Giving the points based on the number of attempts
//
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

import java.util.Random;
import java.util.Scanner;


///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Class used:    Random
//Function Used:  rand()
// Description:   The class Random provides a functionality to generate Random numbers.
//                Random number generation algorithm works on the seed value.
//                 If the seed value is not provided it is created from system nano time.
// Parameter:     This function does not take any parameters.
// Return Value:  rand() returns a pseudo-random number in the range of [0, RAND_MAX).
// Author:        Shruti Vaibhav Bartakke
// Date:          11/08/2023   
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////    

public class NumberGame
{

/////////////////////////////////////////////////////////////////////////////////
//  Entry Point function
/////////////////////////////////////////////////////////////////////////////////

    public static void main(String[] args)
    {
        int iAns, iGuess, iChance = 5;
        int iRound = 3;
        int iVar = 1;
        int iScore = 0;
        final int Max = 50;

        System.out.println("----WELCOME TO GUESS THE NUMBER GAME----");
        System.out.println("-----HOW TO PLAY-------");
        System.out.println("You have to guess the number generated by the computer.\n If you win the game stops\n");
        System.out.println("-----RULES OF GAME-----");
        System.out.println("1.Toatal Rounds will be 3");
        System.out.println("2.Each Round will have 5 chances to guess the number correct");
        System.out.println("3.You are not allowed to enter a number greater than 50");
        System.out.println("\n\nStart Playing!!!\n\n");
  do
  {
    System.out.println("--------------------------------------------------");
    System.out.println("Rounds Remaining: "+iRound);
    System.out.println("--------------------------------------------------");
    System.out.println("--------------------------------------------------");
    System.out.println("Chances Remaining to Guess: "+iChance);
    System.out.println("--------------------------------------------------");

        Scanner keyboard = new Scanner(System.in);
        Random rand = new Random();
        
        iAns = rand.nextInt(Max) + 1;

        System.out.println("\nPlease Guess the number between 1 to 50");
        iGuess =keyboard.nextInt();
         
        if(iGuess > 50)
        {
            System.out.println("Invalid Input");
            System.out.println("Kindly enter the number between 1-50\n");
        }
        if(iGuess == iAns)
        {
            System.out.println("Hurrah!!You Won");
            System.out.println("The number was "+iAns);
            iVar = 0;
        }

        else if((iGuess < 50) && (iGuess < iAns))
        {
            System.out.println("System says: Try a smaller number");
            System.out.println("Oops! Sorry, but the number was "+iAns);
        }

        else if((iGuess < 50) && (iGuess > iAns))
        {
            System.out.println("\nSystem says: Try a greater number");
            System.out.println("Oops! Sorry, but the number was "+iAns+"\n");  
        }

        if(iGuess < 50)
        {
        iChance--;
        }

        if(iChance == 0)
        {
            iRound--;
           iChance = 5;    
           
        }
    
        
    }while((iRound != 0) && (iVar == 1) );

    if((iRound == 0) && (iGuess != iAns))
    {
    System.out.println("\nSorry, no chances left");
    System.out.println("Better Luck next time!");
    }
    
    System.out.println("Thank you for using our game");
}
}